# To read this file do:
# $ perldoc README

=head1 NAME

=begin HTML

<p><a href="https://gitter.im/eprints/eprints?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"><img src="https://badges.gitter.im/Join%20Chat.svg" alt="Join the chat at https://gitter.im/eprints/eprints"></a></p>

=end HTML

GNU EPrints README

=head1 SYNOPSIS

	./configure --help
	./configure (with some sensible options)
	sudo make install

Installation guide: B<http://wiki.eprints.org/w/Installation>.

For more information see B<http://www.eprints.org/software/>.

=head1 DESCRIPTION

EPrints is a document management system aimed at Higher Educational
institutions and individuals. EPrints has been used to provide Open Access
to research results, sharing of educational resources and providing
portfolios of work. It has a flexible metadata and workflow model to
support varied business needs as well as interaction with other Web and
institutional systems.

=head1 CONTACT

For support options please see B<http://www.eprints.org/software/>.

Enquiries that can not be made via our public mailing list (e.g. security
concerns) may be sent to B<support@eprints.org>.

EPrints can be contacted in the real world at

	EPrints Services
	Electronics and Computer Science
	Faculty of Physical Sciences and Engineering
	University of Southampton
	Southampton, SO17 1BJ
	United Kingdom

=head1 COPYRIGHT

Copyright 2000-2015 University of Southampton.

EPrints is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

EPrints is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
License for more details.

You should have received a copy of the GNU General Public License
along with EPrints.  If not, see L<http://www.gnu.org/licenses/>.
