#!/usr/bin/perl -w -I/opt/eprints3/perl_lib

use EPrints;

use strict;

my $handle = EPrints->get_repository_handle();
exit( 1 ) unless( defined $handle );

my $url = "http://www.google.com/search?q=".$handle->param( "q" );
$url .= "+site:".$handle->get_repository->get_conf( "host" );

$handle->redirect( $url );

$handle->terminate();
