#!/usr/bin/perl -w -I/opt/eprints2/perl_lib

use EPrints::Session;

use strict;

my $session = new EPrints::Session();
exit( 1 ) unless( defined $session );

my $url = "http://www.google.com/search?q=".$session->param( "q" );
$url .= "+site:".$session->get_archive->get_conf( "host" );

$session->redirect( $url );

$session->terminate();
