#!/usr/bin/perl

use EPrints;

my $handle = EPrints->get_handle();
exit( 0 ) unless( defined $handle );

print_xsd( $handle );

$handle->terminate;

sub print_xsd
{
	my( $handle ) = @_;

	my $dataset = $handle->get_repository->get_dataset( "metafield" );

	my $plugin = $handle->plugin( "Export::XML_Schema" );

	my $list = EPrints::List->new(
		dataset => $dataset,
		handle => $handle,
		ids=>["ALL"] );

	$handle->send_http_header( "content_type" => "application/xml" );
	$plugin->initialise_fh( \*STDOUT );
	$plugin->output_list( list=>$list, fh=>*STDOUT );

	$list->dispose;
}
