#!/usr/bin/perl

use EPrints;

use strict;

my $repo = EPrints->new->current_repository;

my $url = $repo->param( "target" );

#unset $url if it doesn't have the same hostname as the repository
if (defined $url)
{
        my $target_uri = URI->new($url);
        my $repository_uri = URI->new($repo->config('base_url'));
        if ($target_uri->host ne $repository_uri->host)
        {
                $url = undef;
        }
}

$url = $repo->config( "http_cgiroot" ) . "/users/home" if !defined $url;

$repo->redirect( $url );
